export const iconsTour = {
  Cruise: require('@/assets/images/Cruise.png'),
  Cycling: require('@/assets/images/Cycling.png'),
  Cyclo: require('@/assets/images/Cyclo.png'),
  DragonBoat: require('@/assets/images/Dragon-Boat.png'),
  ElectricBoat: require('@/assets/images/Electric-Boat.png'),
  Flight: require('@/assets/images/Flight.png'),
  Hotel: require('@/assets/images/Hotel.png'),
  MealBLD: require('@/assets/images/Meal BLD.png'),
  Motorcycle: require('@/assets/images/Motorcycle.png'),
  Ship: require('@/assets/images/Ship.png'),
  Train: require('@/assets/images/Train.png'),
  Trekking: require('@/assets/images/Trekking.png'),
  Tuktuk: require('@/assets/images/Tuktuk.png'),
  Walking: require('@/assets/images/Walking.png'),
  Zipline: require('@/assets/images/Zipline.png'),
  Jeep: require('@/assets/images/Jeep.png'),
  Kayak: require('@/assets/images/Kayak.png'),
  RowlingBoat: require('@/assets/images/Rowling-Boat.png'),
  HotAirBalloon: require('@/assets/images/hot-air-balloon.png'),
  Car: require('@/assets/images/Car.png'),
  Bus: require('@/assets/images/Bus.png'),
}
